@startuml

title Dialog Triggers Class Diagram

class ADialogTrigger {
  +void OnConstruction(FTransform Transform)
  +void SendDialogToHUD(AHUD* HUD, FDataTableRowHandle DialogRowHandle)
  +void OnBeginOverlap(args...)
  +void SendDialog()
  +TSubclassOf<UBaseDialogPickStrategy> DialogStrategyClass
  +TObjectPtr<UBaseDialogPickStrategy> DialogStrategy
  +TSubclassOf<UBaseTriggerStateStrategy> StateStrategyClass
  +TObjectPtr<UBaseTriggerStateStrategy> StateStrategy
}

class UBaseTriggerStateStrategy {
  +bool IsActive()
  +void OnTrigger()
}

class UBaseDialogPickStrategy {
  +FDataTableRowHandle GetDialog()
}

class URandomListDialogPickStrategy {
  +FDataTableRowHandle GetDialog()
  +TArray<FDataTableRowHandle> DialogList
}

class USingleDialogPickStrategy {
  +FDataTableRowHandle GetDialog()
  +FDataTableRowHandle Dialog
}

class UCooldownStrategy {
  +bool IsActive()
  +void OnTrigger()
  +float PlayBackCooldown = 5.0f
  +bool Active = true
  +FTimerHandle DelayTimerHandle
}

class USingleShotStrategy {
  +bool IsActive()
  +void OnTrigger()
  +bool Active = true
}

ADialogTrigger --|> UBaseTriggerStateStrategy
ADialogTrigger --|> UBaseDialogPickStrategy

UBaseTriggerStateStrategy --|> UCooldownStrategy
UBaseTriggerStateStrategy --|> USingleShotStrategy

UBaseDialogPickStrategy --|> USingleDialogPickStrategy
UBaseDialogPickStrategy --|> URandomListDialogPickStrategy


note left of ADialogTrigger
Basic Dialog trigger, holds two strategies that defines its behaviour
end note

note left of UBaseTriggerStateStrategy
Controls how often trigger will be executed 
(once, with the cooldown, depending of item inventory, or grabber inventory)
end note

note left of UBaseDialogPickStrategy
Controls which dialog is sent to HUD (only one, one from list)
end note

@enduml